In [1]:
import gym
import numpy as np

### Load the environment using openAI gym

In [2]:
env = gym.make('FrozenLake-v0')

[2017-10-04 03:03:40,119] Making new env: FrozenLake-v0


### Implement Q-Learning Algorithm using bellman equation

In [7]:
#Initialize table with all zeros
Q = np.zeros([env.observation_space.n,env.action_space.n])
# Set learning parameters
lr = .8
y = .95
num_episodes = 2
#create lists to contain total rewards and steps per episode
#jList = []
rList = []
for i in range(num_episodes):
    #Reset environment and get first new observation
    s = env.reset()
    rAll = 0
    d = False
    j = 0
    #The Q-Table learning algorithm
    while j < 99:
        j+=1
        #Choose an action by greedily (with noise) picking from Q table
        a = np.argmax(Q[s,:] + np.random.randn(1,env.action_space.n)*(1./(i+1)))
        #Get new state and reward from environment
        s1,r,d,_ = env.step(a)
        #Update Q-Table with new knowledge
        Q[s,a] = Q[s,a] + lr*(r + y*np.max(Q[s1,:]) - Q[s,a])
        rAll += r
        s = s1
        if d == True:
            break
    #jList.append(j)
    rList.append(rAll)

0
0
0
0
0
1
1
0
0
1
2
2
6
2
2
6
7
1
2
3
7


In [4]:
print "Score over time: " +  str(sum(rList)/num_episodes)

Score over time: 0.3795


In [5]:
print "Final Q-Table Values"
print Q

Final Q-Table Values
[[  8.64144396e-02   6.88516356e-03   4.22123340e-03   5.33982110e-03]
 [  7.28388125e-04   3.07765239e-04   1.88341422e-04   1.34067925e-01]
 [  2.27889370e-03   1.37785740e-03   3.69155393e-03   1.59937886e-01]
 [  1.44574309e-04   7.36194127e-04   6.15138265e-04   8.02570554e-02]
 [  7.90768580e-02   7.71915673e-04   4.03463520e-03   2.03248029e-04]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  8.47810105e-04   7.99597289e-05   1.30157844e-01   1.77933972e-05]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  4.04386930e-05   1.17201340e-05   9.37542768e-04   1.30174759e-01]
 [  0.00000000e+00   1.19934761e-01   1.09391082e-04   3.56502104e-04]
 [  5.69760169e-01   5.10761887e-05   4.76005100e-05   6.81023249e-05]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  4.23763410e-04   0.00000000e+00   3.25436454e-01   0